version: '3.8'

services:
  app:
    build: .
    container_name: irfani-events-app
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=${MONGODB_URI}
    restart: unless-stopped
    networks:
      - irfani-net

networks:
  irfani-net:
    driver: bridge
